require 'rspec/matchers'
require 'machete/matchers/be_running'
require 'machete/matchers/have_body'
require 'machete/matchers/have_file'
require 'machete/matchers/have_internet_traffic'
require 'machete/matchers/have_logged'
